name 'aws_cli'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures aws_cli'
long_description 'Installs/Configures aws_cli'
version '0.1.1'
